// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

// Security: Ensure Lovable auth is initialized client-side only
// Never expose LOVABLE_API_KEY to the client
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

/**
 * Validates redirect URI to prevent open redirect vulnerabilities
 */
function isValidRedirectUri(uri: string): boolean {
  try {
    const url = new URL(uri, window.location.origin);
    // Only allow same-origin redirects
    return url.origin === window.location.origin;
  } catch {
    return false;
  }
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      // Validate redirect_uri to prevent open redirect attacks
      const redirectUri = opts?.redirect_uri || window.location.origin;
      if (!isValidRedirectUri(redirectUri)) {
        return { error: new Error("Invalid redirect URI") };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: redirectUri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
